[package]
name = "time_converter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.74"
chrono = { version = "0.4.19", features = ["wasmbind"] }

[lib]
crate-type = ["cdylib"]